# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86153\Desktop\Database\Lab\Lab2\lab\manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox
from connect import *
import time
from datetime import datetime, timedelta

cursor, conn = connect()  # 连接数据库


class Ui_Mangager(object):
    def setupUi(self, Mangager):
        Mangager.setObjectName("Mangager")
        self.workerid = self.mid
        Mangager.resize(881, 740)
        self.centralwidget = QtWidgets.QWidget(Mangager)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(120, 70, 671, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 140, 671, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(80, 20, 121, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(230, 20, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 20, 131, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(122, 70, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(322, 67, 171, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(450, 20, 72, 15))
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(500, 20, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 20, 121, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 60, 121, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 100, 121, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(230, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(230, 60, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(280, 60, 121, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(220, 100, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(280, 100, 121, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(430, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(510, 20, 121, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(430, 60, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(510, 60, 121, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(430, 100, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(510, 100, 121, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 140, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(100, 140, 121, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 140, 71, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(530, 140, 71, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(450, 140, 61, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 190, 671, 351))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(10)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(270, 140, 71, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_15.setGeometry(QtCore.QRect(280, 20, 121, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(30, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(90, 20, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(280, 20, 72, 15))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(240, 20, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_13.setGeometry(QtCore.QRect(290, 20, 113, 21))
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(440, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(530, 20, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 120, 671, 421))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setVerticalHeaderItem(4, item)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(352, 70, 101, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tab_3, "")
        Mangager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Mangager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 26))
        self.menubar.setObjectName("menubar")
        Mangager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Mangager)
        self.statusbar.setObjectName("statusbar")
        Mangager.setStatusBar(self.statusbar)

        self.retranslateUi(Mangager)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Mangager)

        # frontend/manager.py
        #读者查询链接
        self.pushButton.clicked.connect(self.selectreader)
        #全部读者查询链接
        self.pushButton_2.clicked.connect(self.selectallreader)
        #显示全部书籍连接
        self.pushButton_7.clicked.connect(self.selectallbook)
        #删除书籍链接
        self.pushButton_4.clicked.connect(self.deletebook)
        #增加书籍链接
        self.pushButton_6.clicked.connect(self.addbook)
        #修改书籍链接
        self.pushButton_5.clicked.connect(self.changebook)
        #个人信息修改
        self.pushButton_8.clicked.connect(self.changedata)
        #个人信息查询
        self.pushButton_3.clicked.connect(self.selectinformation)
        # 使书籍表中鼠标点击操作选中的是一行而不是一格
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        # 使书籍表中鼠标双击行的时候不可直接更改
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableWidget_2.activated.connect(self.displaybook)

    def retranslateUi(self, Mangager):
        _translate = QtCore.QCoreApplication.translate
        Mangager.setWindowTitle(_translate("Mangager", "Mangager"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Mangager", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Mangager", "读者号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Mangager", "性别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Mangager", "系别"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Mangager", "可借册数"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Mangager", "在借册数"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Mangager", "欠款"))
        self.label.setText(_translate("Mangager", "姓名"))
        self.label_2.setText(_translate("Mangager", "读者号"))
        self.pushButton.setText(_translate("Mangager", "根据条件查询"))
        self.pushButton_2.setText(_translate("Mangager", "查询所有（无需条件）"))
        self.label_3.setText(_translate("Mangager", "系别"))
        self.comboBox.setItemText(0, _translate("Mangager", "计算机系"))
        self.comboBox.setItemText(1, _translate("Mangager", "数学系"))
        self.comboBox.setItemText(2, _translate("Mangager", "物理系"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Mangager", "读者信息"))
        self.label_4.setText(_translate("Mangager", "书名"))
        self.label_5.setText(_translate("Mangager", "书号"))
        self.label_6.setText(_translate("Mangager", "作者"))
        self.label_7.setText(_translate("Mangager", "类型"))
        self.label_8.setText(_translate("Mangager", "价格"))
        self.label_9.setText(_translate("Mangager", "出版社"))
        self.label_10.setText(_translate("Mangager", "馆藏册数"))
        self.label_11.setText(_translate("Mangager", "在馆册数"))
        self.label_12.setText(_translate("Mangager", "位置"))
        self.label_13.setText(_translate("Mangager", "被借次数"))
        self.pushButton_4.setText(_translate("Mangager", "删除"))
        self.pushButton_5.setText(_translate("Mangager", "修改"))
        self.pushButton_6.setText(_translate("Mangager", "增加"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Mangager", "书名"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Mangager", "书号"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Mangager", "作者"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Mangager", "类型"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Mangager", "价格"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Mangager", "出版社"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Mangager", "馆藏册数"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Mangager", "在馆册数"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Mangager", "位置"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("Mangager", "被借次数"))
        self.pushButton_7.setText(_translate("Mangager", "显示所有"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Mangager", "书籍信息"))
        self.label_14.setText(_translate("Mangager", "手机号"))
        self.label_15.setText(_translate("Mangager", "密码"))
        self.label_17.setText(_translate("Mangager", "确认新密码"))
        self.pushButton_8.setText(_translate("Mangager", "确认修改"))
        item = self.tableWidget_3.verticalHeaderItem(0)
        item.setText(_translate("Mangager", "管理号"))
        item = self.tableWidget_3.verticalHeaderItem(1)
        item.setText(_translate("Mangager", "姓名"))
        item = self.tableWidget_3.verticalHeaderItem(2)
        item.setText(_translate("Mangager", "性别"))
        item = self.tableWidget_3.verticalHeaderItem(3)
        item.setText(_translate("Mangager", "手机号"))
        item = self.tableWidget_3.verticalHeaderItem(4)
        item.setText(_translate("Mangager", "密码"))
        self.pushButton_3.setText(_translate("Mangager", "信息查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Mangager", "个人信息"))

    # 根据条件查询读者
    def selectreader(self):
        readername = self.lineEdit.text()
        readerid = self.lineEdit_2.text()
        readerpartment = self.comboBox.currentText()
        # 进行条件sql语句编写
        inherit = 0
        if readername:
            readername_sql = ' 姓名="%s"' % (readername)
            inherit = 1
        else:
            readername_sql = ''
        if readerid:
            if inherit == 1:
                readerid_sql = ' and 读者号="%s"' % (readerid)
            else:
                readerid_sql = ' 读者号="%s"' % (readerid)
                inherit = 1
        else:
            readerid_sql=''
        if readerpartment:
            if inherit == 1:
                readerpartment_sql = 'and 系别="%s"' % (readerpartment)
            else:
                readerpartment_sql = ' 系别="%s"' % (readerpartment)
                inherit = 1
        else:
            readerpartment_sql=''
        sql_end = readername_sql + readerid_sql + readerpartment_sql
        if sql_end:
            sql_base = 'SELECT * FROM readers where'
            sql = sql_base + sql_end
            res = cursor.execute(sql)
            readers = cursor.fetchall()
            if res:
                readernumber = len(readers)
                self.tableWidget.setRowCount(readernumber)
                for i in range(readernumber):
                    reader = readers[i]
                    print(reader)
                    self.tableWidget.setItem(i, 0, QtWidgets.QTableWidgetItem(str(reader[1])))
                    self.tableWidget.setItem(i, 1, QtWidgets.QTableWidgetItem(str(reader[0])))
                    self.tableWidget.setItem(i, 2, QtWidgets.QTableWidgetItem(str(reader[2])))
                    self.tableWidget.setItem(i, 3, QtWidgets.QTableWidgetItem(str(reader[3])))
                    self.tableWidget.setItem(i, 4, QtWidgets.QTableWidgetItem(str(reader[4])))
                    self.tableWidget.setItem(i, 5, QtWidgets.QTableWidgetItem(str(reader[5])))
                    self.tableWidget.setItem(i, 6, QtWidgets.QTableWidgetItem(str(reader[7])))
            else:
                QMessageBox.warning(self, "警告", "没有符合条件的读者！", QMessageBox.Yes)
        else:
            QMessageBox.warning(self, "警告", "请输入查询条件！", QMessageBox.Yes)
    
    #查询所有读者
    def selectallreader(self):
        sql = 'SELECT * FROM readers'
        cursor.execute(sql)
        readers = cursor.fetchall()
        readernumber = len(readers)
        self.tableWidget.setRowCount(readernumber)
        for i in range(readernumber):
            reader = readers[i]
            self.tableWidget.setItem(i, 0, QtWidgets.QTableWidgetItem(str(reader[1])))
            self.tableWidget.setItem(i, 1, QtWidgets.QTableWidgetItem(str(reader[0])))
            self.tableWidget.setItem(i, 2, QtWidgets.QTableWidgetItem(str(reader[2])))
            self.tableWidget.setItem(i, 3, QtWidgets.QTableWidgetItem(str(reader[3])))
            self.tableWidget.setItem(i, 4, QtWidgets.QTableWidgetItem(str(reader[4])))
            self.tableWidget.setItem(i, 5, QtWidgets.QTableWidgetItem(str(reader[5])))
            self.tableWidget.setItem(i, 6, QtWidgets.QTableWidgetItem(str(reader[7])))
    
    # 查询所有书籍
    def selectallbook(self):
        sql = 'SELECT * FROM books'
        cursor.execute(sql)
        books = cursor.fetchall()
        booknumber = len(books)
        self.tableWidget_2.setRowCount(booknumber)
        for i in range(booknumber):
            book = books[i]
            print(book)
            self.tableWidget_2.setItem(i, 0, QTableWidgetItem(str(book[1])))
            self.tableWidget_2.setItem(i, 1, QTableWidgetItem(str(book[0])))
            self.tableWidget_2.setItem(i, 2, QTableWidgetItem(str(book[2])))
            self.tableWidget_2.setItem(i, 3, QTableWidgetItem(str(book[3])))
            self.tableWidget_2.setItem(i, 4, QTableWidgetItem(str(book[4])))
            self.tableWidget_2.setItem(i, 5, QTableWidgetItem(str(book[5])))
            self.tableWidget_2.setItem(i, 6, QTableWidgetItem(str(book[6])))
            self.tableWidget_2.setItem(i, 7, QTableWidgetItem(str(book[7])))
            self.tableWidget_2.setItem(i, 8, QTableWidgetItem(str(book[8])))
            self.tableWidget_2.setItem(i, 9, QTableWidgetItem(str(book[9])))
    
    #删除书籍
    def deletebook(self):
        currentline = self.tableWidget_2.currentRow() 
        bookid = self.tableWidget_2.item(currentline, 1).text()
        sql = 'delete from books where 书号="%s"' % (bookid)
        res = cursor.execute(sql)
        sql = 'delete from borrow where 书号="%s"' % (bookid)
        res = cursor.execute(sql)
        conn.commit()
        self.selectallbook()

    #将书籍信息显示在行中
    def displaybook(self):
        currentline = self.tableWidget_2.currentRow()
        self.lineEdit_3.setText(self.tableWidget_2.item(currentline,0).text())
        self.lineEdit_4.setText(self.tableWidget_2.item(currentline,1).text())
        self.lineEdit_5.setText(self.tableWidget_2.item(currentline,2).text())
        self.lineEdit_15.setText(self.tableWidget_2.item(currentline,3).text())
        self.lineEdit_7.setText(self.tableWidget_2.item(currentline,4).text())
        self.lineEdit_8.setText(self.tableWidget_2.item(currentline,5).text())
        self.lineEdit_9.setText(self.tableWidget_2.item(currentline,6).text())
        self.lineEdit_10.setText(self.tableWidget_2.item(currentline,7).text())
        self.lineEdit_11.setText(self.tableWidget_2.item(currentline,8).text())
        self.lineEdit_12.setText(self.tableWidget_2.item(currentline,9).text())

    #添加书籍
    def addbook(self):
        name = self.lineEdit_3.text()
        num = self.lineEdit_4.text()
        author = self.lineEdit_5.text()
        type = self.lineEdit_15.text()
        price_ = self.lineEdit_7.text()
        press = self.lineEdit_8.text()
        library_num = int(self.lineEdit_9.text())
        library_num_res = int(self.lineEdit_10.text())
        loca = self.lineEdit_11.text()
        times = self.lineEdit_12.text()
        if library_num < library_num_res:
            QMessageBox.warning(self, "警告", "书目数量有误！", QMessageBox.Yes)
        else:
            sql = 'select * from books where 书号="%s"' % num
            res = cursor.execute(sql)
            print(res)
            if res:
                QMessageBox.warning(self, "警告", "书号已存在！", QMessageBox.Yes)
            else:
                if price_ != None:
                    price = float(price_)
                    if(name and num and author and type and price and press and library_num and library_num_res and loca and times):
                        sql = 'insert into books(书名,书号,作者,类型,价格,出版社,馆藏册数,在馆册数,位置,被借次数) values("%s","%s","%s","%s","%.2f","%s","%s","%s","%s","%s")' % (name, num, author, type, price, press, library_num, library_num_res, loca, times)

                        cursor.execute(sql)
                        conn.commit()
                        self.selectallbook()
                    else:
                        QMessageBox.warning(self, "警告", "请补全书目信息！", QMessageBox.Yes)
                else:
                    QMessageBox.warning(self, "警告", "请补全书目信息！", QMessageBox.Yes)
    
    #修改书籍
    def changebook(self):
        name = self.lineEdit_3.text()
        num = self.lineEdit_4.text()
        author = self.lineEdit_5.text()
        type = self.lineEdit_15.text()
        price_ = self.lineEdit_7.text()
        press = self.lineEdit_8.text()
        library_num = int(self.lineEdit_9.text())
        library_num_res = int(self.lineEdit_10.text())
        loca = self.lineEdit_11.text()
        times = self.lineEdit_12.text()
        if library_num < library_num_res:
            QMessageBox.warning(self, "警告", "书目数量有误！", QMessageBox.Yes)
        else:
            if price_ != None:
                price = float(price_)
                if(name and num and author and type and price and press and library_num and library_num_res and loca and times):
                    sql = 'update books set 作者="%s",类型="%s",价格="%s",出版社="%s",馆藏册数="%s",在馆册数="%s",位置="%s",被借次数="%s",书名="%s" where 书号="%s"' % (author, type, price, press, library_num, library_num_res, loca, times, name, num)
                    cursor.execute(sql)
                    conn.commit()
                    self.selectallbook()
                    self.displaybook()
                else:
                    QMessageBox.warning(self, "警告", "请补全书目信息！", QMessageBox.Yes)
            else:
                QMessageBox.warning(self, "警告", "请补全书目信息！", QMessageBox.Yes)
    
    #个人信息修改
    def changedata(self):
        new_number = self.lineEdit_6.text()
        new_password = self.lineEdit_13.text()
        new_password_confirm = self.lineEdit_14.text()
        inherit = 0
        if new_number:
            number_sql = 'set 手机号="%s"' % new_number
            inherit = 1
        else:
            number_sql = ''
        if new_password:
            if new_password != new_password_confirm:
                QMessageBox.warning(self, "警告", "重新确认密码！", QMessageBox.Yes)
                password_sql = ''
            else:
                if inherit:
                    password_sql = ', 密码="%s"' % new_password
                else:
                    password_sql = 'set 密码="%s"' % new_password
                    inherit = 1
        else:
            password_sql = ''
        base_sql = 'update workers ' 
        end_sql = ' where 管理号="%s"' % self.workerid
        sql = base_sql + number_sql + password_sql + end_sql  
        print(sql)
        if inherit == 1:
            cursor.execute(sql)
            conn.commit()
            QMessageBox.warning(self, "提示", "修改成功！", QMessageBox.Yes)
        else:
            QMessageBox.warning(self, "警告", "请输入信息！", QMessageBox.Yes)
    
    # 个人信息查询
    def selectinformation(self):
        sql = 'select * from workers where 管理号="%s"' % self.workerid
        res = cursor.execute(sql)
        worker = cursor.fetchall()
        person = worker[0]
        count = len(person)
        self.tableWidget_3.setColumnCount(1)
        for i in range(count):
            self.tableWidget_3.setItem(i,0,QTableWidgetItem(person[i]))