# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86153\Desktop\Database\Lab\Lab2\lab\manager_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox
from connect import *

cursor, conn = connect()  # 连接数据库


class Ui_Manager_Register(object):
    def setupUi(self, Manager_Register):
        Manager_Register.setObjectName("Manager_Register")
        Manager_Register.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        Manager_Register.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Manager_Register)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 30, 191, 91))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 120, 72, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 360, 72, 21))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 350, 151, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(6)
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 410, 72, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 400, 151, 41))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 460, 151, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 190, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 120, 151, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(300, 180, 151, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 250, 72, 15))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(300, 240, 151, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 300, 72, 15))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 290, 151, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        Manager_Register.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Manager_Register)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        Manager_Register.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Manager_Register)
        self.statusbar.setObjectName("statusbar")
        Manager_Register.setStatusBar(self.statusbar)

        self.retranslateUi(Manager_Register)
        QtCore.QMetaObject.connectSlotsByName(Manager_Register)

        self.pushButton.clicked.connect(self.manager_register)

    def retranslateUi(self, Manager_Register):
        _translate = QtCore.QCoreApplication.translate
        Manager_Register.setWindowTitle(_translate("Manager_Register", "Manager_Register"))
        self.label.setText(_translate("Manager_Register", "管理员注册"))
        self.label_2.setText(_translate("Manager_Register", "用户ID"))
        self.label_3.setText(_translate("Manager_Register", "密码"))
        self.label_4.setText(_translate("Manager_Register", "确认密码"))
        self.pushButton.setText(_translate("Manager_Register", "注册"))
        self.label_5.setText(_translate("Manager_Register", "姓名"))
        self.label_6.setText(_translate("Manager_Register", "性别"))
        self.label_7.setText(_translate("Manager_Register", "手机号码"))

    def manager_register(self):
        managerid = self.lineEdit_3.text()
        managername = self.lineEdit_4.text()
        managersex = self.lineEdit_5.text()
        managernumber = self.lineEdit_6.text()
        managerpassword = self.lineEdit.text()
        managerpassword_confirm = self.lineEdit_2.text()
        if managerid == None or managername == None:
            QMessageBox.warning(self, "警告", "姓名和ID不能为空！", QMessageBox.Yes)
        if managerpassword != managerpassword_confirm:
            QMessageBox.warning(self, "警告", "请重新输入密码！", QMessageBox.Yes)
        sql = 'select * from workers where 管理号 = "%s"' % managerid
        res = cursor.execute(sql)
        if res:
            QMessageBox.warning(self, "警告", "该管理号已存在！", QMessageBox.Yes)
        else:
            sql = 'insert into workers() values ("%s", "%s", "%s", "%s", "%s")' % (managerid, managername, managersex, managernumber, managerpassword)
            res = cursor.execute(sql)
            conn.commit()
            QMessageBox.warning(self, "提醒", "注册成功！", QMessageBox.Yes)
        
