# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\86153\Desktop\Database\Lab\Lab2\lab\reader_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox
from connect import *

cursor, conn = connect()  # 连接数据库


class Ui_Reader_Register(object):
    def setupUi(self, Reader_Register):
        Reader_Register.setObjectName("Reader_Register")
        Reader_Register.resize(760, 555)
        self.centralwidget = QtWidgets.QWidget(Reader_Register)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 171, 71))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 72, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 290, 51, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 460, 121, 41))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 290, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        self.lineEdit.setFont(font)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 350, 72, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 350, 161, 31))
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 140, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 130, 161, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 190, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 180, 161, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(310, 230, 161, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 250, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(310, 80, 161, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 410, 72, 15))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(310, 400, 161, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        Reader_Register.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Reader_Register)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 26))
        self.menubar.setObjectName("menubar")
        Reader_Register.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Reader_Register)
        self.statusbar.setObjectName("statusbar")
        Reader_Register.setStatusBar(self.statusbar)

        self.retranslateUi(Reader_Register)
        QtCore.QMetaObject.connectSlotsByName(Reader_Register)

        
        #注册按键链接
        self.pushButton.clicked.connect(self.reader_register)
        
    def retranslateUi(self, Reader_Register):
        _translate = QtCore.QCoreApplication.translate
        Reader_Register.setWindowTitle(_translate("Reader_Register", "Reader_Register"))
        self.label.setText(_translate("Reader_Register", "借阅者注册"))
        self.label_2.setText(_translate("Reader_Register", "用户ID"))
        self.label_3.setText(_translate("Reader_Register", "密码"))
        self.pushButton.setText(_translate("Reader_Register", "注册"))
        self.label_4.setText(_translate("Reader_Register", "确认密码"))
        self.label_5.setText(_translate("Reader_Register", "姓名"))
        self.label_6.setText(_translate("Reader_Register", "性别"))
        self.label_7.setText(_translate("Reader_Register", "系别"))
        self.label_8.setText(_translate("Reader_Register", "照片地址"))

    def reader_register(self):
        readerid = self.lineEdit_6.text()
        readername = self.lineEdit_3.text()
        readersex = self.lineEdit_4.text()
        readerpartment = self.lineEdit_5.text()
        readerpassword = self.lineEdit.text()
        readerpassword_confirm = self.lineEdit_2.text()
        img = self.lineEdit_7.text()
        if readerid == None or readername == None:
            QMessageBox.warning(self, "警告", "姓名和ID不能为空！", QMessageBox.Yes)
        if readerpassword != readerpassword_confirm:
            QMessageBox.warning(self, "警告", "请重新输入密码！", QMessageBox.Yes)
        sql = 'select * from readers where 读者号 = "%s"' % readerid
        res = cursor.execute(sql)
        if res:
            QMessageBox.warning(self, "警告", "该读者号已存在！", QMessageBox.Yes)
        else:
            sql = 'call setimg("%s","%s","%s","%s","%s","%s")' % (img,readerid, readername, readersex, readerpartment, readerpassword)
            res = cursor.execute(sql)
            conn.commit()
            QMessageBox.warning(self, "提醒", "注册成功！", QMessageBox.Yes)
